name: ###

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  iconly: ^1.0.1
  image_picker: ^0.8.9
  lottie: ^2.4.0
  material_dialogs: ^1.1.4
  meta: ^1.9.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

flutter_native_splash:
  background_image: assets/images/limit.png
  android_12:
    image: assets/images/limit.png
  fullscreen: true
